[env]
X86_64_APPLE_DARWIN_OPENSSL_DIR = "/usr/local/opt/openssl@3"
X86_64_APPLE_DARWIN_OPENSSL_LIB_DIR = "/usr/local/opt/openssl@3/lib"
X86_64_APPLE_DARWIN_OPENSSL_INCLUDE_DIR = "/usr/local/opt/openssl@3/include"
PKG_CONFIG_PATH = "/usr/local/opt/openssl@3/lib/pkgconfig"


